CREATE TABLE TMAETRACAL(
	Cod_Trabajo integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Mat_Trabajo varchar NOT NULL,
    Prof_Trabajo varchar NOT NULL,
    Act_Trabajo varchar NOT NULL,
    Des_Trabajo varchar NOT NULL,
    FeI_Trabajo varchar NOT NULL,
    FeC_Trabajo varchar NOT NULL,
    Cur_Trabajo varchar NOT NULL
);

SELECT * FROM TMAETRACAL;

TRUNCATE TABLE TMAETRACAL RESTART IDENTITY;
